/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * OZT2-first CesiumJS terrain provider.
 *
 * Fetches OZT2 tiles from the server (R2 or edge-generated) using the native
 * DecompressionStream API — no WASM needed in modern browsers.
 *
 * OZT2 tiles are pre-generated by scripts/convert_to_ozt2.py and stored in R2.
 * The edge runtime cannot Brotli-compress on-the-fly, so OZT2 tiles must exist
 * in R2 before the request. If no OZT2 tile is found, falls back to PNG tiles.
 *
 * Falls back to CSR-direct (HuggingFace) if the server has no OZT2 tile.
 *
 * Uses CesiumJS 1.119's HeightmapTerrainData (not quantized-mesh).
 */

import { decodeOZT2 } from "@/lib/ozt2_decode";

type CesiumType = any;

const TERRAIN_URL = "/api/dem-tile";
const MAX_TERRAIN_ZOOM = 12;

const HEIGHTMAP_STRUCTURE = {
  heightScale: 1.0,
  heightOffset: 0.0,
  elementsPerHeight: 1,
  stride: 1,
  elementMultiplier: 1.0,
  isBigEndian: false,
};

/**
 * Create an OZT2-first Cesium terrain provider.
 *
 * Tile fetching order:
 * 1. OZT2 tiles from R2/edge (pre-generated, ~93% smaller than PNG)
 * 2. PNG tiles from R2/edge (on-the-fly generated, legacy)
 * 3. CSR-direct from HuggingFace (browser-side, last resort)
 */
export function createOZTTerrainProvider(Cesium: CesiumType) {
  const TDT = Cesium.HeightmapTerrainData;
  const provider: any = Object.create(Cesium.TerrainProvider.prototype);

  provider.ready = true;
  provider.readyPromise = Promise.resolve(provider);
  Object.defineProperty(provider, "hasVertexNormals", { value: false, writable: true, configurable: true });
  Object.defineProperty(provider, "hasWaterMask", { value: false, writable: true, configurable: true });
  provider.errorEvent = new Cesium.Event();

  provider.requestTileGeometry = function (x: number, y: number, level: number, _request: any) {
    if (level > MAX_TERRAIN_ZOOM || !TDT) {
      return Promise.resolve(null);
    }

    // Try OZT2 first (fast, pre-generated, ~1KB vs ~15KB for PNG)
    return tryOZTTile(Cesium, level, x, y)
      .catch(() => null)
      .then((result: any) => {
        if (result) return result;

        // Fall back to PNG tile (on-the-fly generated from HuggingFace)
        return tryPNGTile(Cesium, level, x, y);
      })
      .catch(() => {
        // Both failed — return flat terrain
        return makeFlatTerrain(Cesium, 256);
      });
  };

  provider.getTileDataAvailable = function (x: number, y: number, level: number) {
    if (level > MAX_TERRAIN_ZOOM) return false;
    return undefined;
  };

  provider.getLevelMaximumGeometricError = function (level: number) {
    return (40075017.0 * 2.0) / ((1 << level) * 65);
  };

  provider.tilingScheme = new Cesium.GeographicTilingScheme({
    ellipsoid: Cesium.Ellipsoid.WGS84,
    numberOfLevelZeroTilesX: 2,
    numberOfLevelZeroTilesY: 1,
  });

  provider.ellipsoid = Cesium.Ellipsoid.WGS84;

  return provider;
}

/**
 * Try to fetch and decode an OZT2 tile.
 * Returns null on failure (network error, no tile in R2, decode error).
 */
async function tryOZTTile(Cesium: CesiumType, level: number, x: number, y: number): Promise<any> {
  const TDT = Cesium.HeightmapTerrainData;
  if (!TDT) return null;

  const url = `${TERRAIN_URL}/${level}/${x}/${y}?format=ozt2`;

  const resource = new Cesium.Resource({ url });
  const response = await resource.fetch();

  if (!response.ok) {
    // No OZT2 tile in R2 — the server may have fallen back to PNG
    // Check if response is a PNG (server returns PNG when OZT2 not in R2)
    const contentType = response.headers.get("content-type") ?? "";
    if (!contentType.includes("octet-stream")) {
      // Server returned PNG as fallback — try PNG path instead
      return tryPNGTile(Cesium, level, x, y);
    }
    return null;
  }

  const arrayBuffer = await response.arrayBuffer();
  if (arrayBuffer.byteLength === 0) return null;

  // Decode OZT2 → Int16Array
  const { elevation } = await decodeOZT2(arrayBuffer);

  // Convert Int16Array → Float32Array for CesiumJS HeightmapTerrainData
  const heights = new Float32Array(elevation.length);
  for (let i = 0; i < elevation.length; i++) {
    heights[i] = elevation[i] === -32768 ? 0 : elevation[i];
  }

  return new TDT({
    buffer: heights,
    width: 256,
    height: 256,
    structure: HEIGHTMAP_STRUCTURE,
    childTileMask: level < MAX_TERRAIN_ZOOM ? 15 : 0,
  });
}

/**
 * Fetch and decode a Terrarium PNG server tile.
 * Used as fallback when OZT2 tile is not available.
 */
async function tryPNGTile(Cesium: CesiumType, level: number, x: number, y: number): Promise<any> {
  const url = `${TERRAIN_URL}/${level}/${x}/${y}`;
  const HDT = Cesium.HeightmapTerrainData;
  if (!HDT) return makeFlatTerrain(Cesium, 256);

  try {
    const response = await Cesium.Resource.fetchImage({ url });
    const w = response.width;
    const h = response.height;
    const canvas = document.createElement("canvas");
    canvas.width = w;
    canvas.height = h;
    const ctx = canvas.getContext("2d")!;
    ctx.drawImage(response, 0, 0);
    const imageData = ctx.getImageData(0, 0, w, h);
    const pixels = imageData.data;

    const heights = new Float32Array(w * h);
    for (let i = 0; i < heights.length; i++) {
      const offset = i * 4;
      const R = pixels[offset];
      const G = pixels[offset + 1];
      const B = pixels[offset + 2];
      heights[i] = R * 256 + G + B / 256 - 32768;
    }

    return new HDT({
      buffer: heights,
      width: w,
      height: h,
      structure: HEIGHTMAP_STRUCTURE,
      childTileMask: level < MAX_TERRAIN_ZOOM ? 15 : 0,
    });
  } catch {
    return makeFlatTerrain(Cesium, 256);
  }
}

function makeFlatTerrain(Cesium: CesiumType, size: number): any {
  const TDT = Cesium.HeightmapTerrainData;
  if (!TDT) return null;
  const flat = new Float32Array(size * size);
  return new TDT({ buffer: flat, width: size, height: size, structure: HEIGHTMAP_STRUCTURE });
}
