/**
 * OZT2-first CesiumJS terrain provider.
 *
 * Fetches OZT2 tiles from the server (R2 or edge-generated) using the native
 * DecompressionStream API — no WASM needed in modern browsers.
 *
 * OZT2 tiles are pre-generated by scripts/convert_to_ozt2.py and stored in R2.
 * The edge runtime cannot Brotli-compress on-the-fly, so OZT2 tiles must exist
 * in R2 before the request. If no OZT2 tile is found, falls back to PNG tiles.
 *
 * Falls back to CSR-direct (HuggingFace) if the server has no OZT2 tile.
 *
 * Uses CesiumJS 1.119's HeightmapTerrainData (not quantized-mesh).
 */

import { decodeOZT2 } from "@/lib/ozt2_decode";

const TERRAIN_URL = "/api/dem-tile";
const MAX_TERRAIN_ZOOM = 12;

const HEIGHTMAP_STRUCTURE = {
  heightScale: 1.0,
  heightOffset: 0.0,
  elementsPerHeight: 1,
  stride: 1,
  elementMultiplier: 1.0,
  isBigEndian: false,
};

/**
 * Structural view of the provider this module assembles by hand over
 * `TerrainProvider.prototype`: `Object.create` returns an object whose members
 * are installed one by one below, so the shape is declared rather than
 * inferred.
 */
interface OZT2TerrainProvider {
  ready: boolean;
  readyPromise: Promise<OZT2TerrainProvider>;
  hasVertexNormals: boolean;
  hasWaterMask: boolean;
  errorEvent: CesiumType.Event;
  credit: CesiumType.Credit;
  availability: undefined;
  loadTileDataAvailability(): undefined;
  requestTileGeometry(
    x: number,
    y: number,
    level: number,
    request: unknown,
  ): Promise<CesiumType.HeightmapTerrainData | null>;
  getTileDataAvailable(x: number, y: number, level: number): boolean | undefined;
  getLevelMaximumGeometricError(level: number): number;
  tilingScheme: CesiumType.GeographicTilingScheme;
  ellipsoid: CesiumType.Ellipsoid;
}

// OZT2 uses -32768 as the NODATA sentinel (standard Int16 nodata)
const OZT2_NODATA = -32768;

/**
 * Create an OZT2-first Cesium terrain provider.
 *
 * Tile fetching order:
 * 1. OZT2 tiles from R2/edge (pre-generated, ~93% smaller than PNG)
 * 2. PNG tiles from R2/edge (on-the-fly generated, legacy)
 * 3. CSR-direct from HuggingFace (browser-side, last resort)
 */
export function createOZTTerrainProvider(Cesium: typeof CesiumType) {
  // Asserted nullable because the guard below tests presence: HeightmapTerrainData
  // is declared as always present, and a const annotated nullable would be
  // narrowed straight back to its initializer.
  const TDT = Cesium.HeightmapTerrainData as typeof CesiumType.HeightmapTerrainData | undefined;
  const provider = Object.create(Cesium.TerrainProvider.prototype) as OZT2TerrainProvider;

  // TerrainProvider.prototype exposes its interface as getter-only accessors
  // in CesiumJS 1.119 — plain assignment throws "Cannot set property X which
  // has only a getter" and aborts the whole globe init. Every member must be
  // defined as an own property to shadow the prototype accessors.
  const def = (key: string, value: unknown) =>
    Object.defineProperty(provider, key, { value, writable: true, configurable: true });

  def("ready", true);
  def("readyPromise", Promise.resolve(provider));
  def("hasVertexNormals", false);
  def("hasWaterMask", false);
  def("errorEvent", new Cesium.Event());
  // credit is read by the render loop every frame for credit display —
  // leaving it to the base-class getter throws DeveloperError and stops
  // rendering. It also carries the data attribution.
  def("credit", new Cesium.Credit("Terrain: SRTM 30m (NASA) via OpenZenith OZT2"));
  def("availability", undefined);
  def("loadTileDataAvailability", function () {
    return undefined;
  });

  def("requestTileGeometry", function (x: number, y: number, level: number, _request: unknown) {
    if (level > MAX_TERRAIN_ZOOM || !TDT) {
      return Promise.resolve(null);
    }

    // Try OZT2 first (fast, pre-generated, ~1KB vs ~15KB for PNG)
    return tryOZTTile(Cesium, level, x, y)
      .catch(() => null)
      .then((result) => {
        if (result) return result;

        // Fall back to PNG tile (on-the-fly generated from HuggingFace)
        return tryPNGTile(Cesium, level, x, y);
      })
      .catch(() => {
        // Both failed — return flat terrain
        return makeFlatTerrain(Cesium, 256);
      });
  });

  def(
    "getTileDataAvailable",
    function (x: number, _y: number, level: number) {
      if (level > MAX_TERRAIN_ZOOM) return false;
      return undefined;
    },
  );

  def("getLevelMaximumGeometricError", function (level: number) {
    return (40075017.0 * 2.0) / ((1 << level) * 65);
  });

  def(
    "tilingScheme",
    new Cesium.GeographicTilingScheme({
      ellipsoid: Cesium.Ellipsoid.WGS84,
      numberOfLevelZeroTilesX: 2,
      numberOfLevelZeroTilesY: 1,
    }),
  );

  def("ellipsoid", Cesium.Ellipsoid.WGS84);

  return provider;
}

/**
 * Try to fetch and decode an OZT2 tile.
 * Returns null on failure (network error, no tile in R2, decode error).
 */
async function tryOZTTile(
  Cesium: typeof CesiumType,
  level: number,
  x: number,
  y: number,
): Promise<CesiumType.HeightmapTerrainData | null> {
  // Same presence assertion as the provider factory above.
  const TDT = Cesium.HeightmapTerrainData as typeof CesiumType.HeightmapTerrainData | undefined;
  if (!TDT) return null;

  const url = `${TERRAIN_URL}/${level}/${x}/${y}?format=ozt2`;

  const resource = new Cesium.Resource({ url });
  const response = await resource.fetch();

  if (!response.ok) {
    // No OZT2 tile in R2 — the server may have fallen back to PNG
    // Check if response is a PNG (server returns PNG when OZT2 not in R2)
    const contentType = response.headers.get("content-type") ?? "";
    if (!contentType.includes("octet-stream")) {
      // Server returned PNG as fallback — try PNG path instead
      return tryPNGTile(Cesium, level, x, y);
    }
    return null;
  }

  const arrayBuffer = await response.arrayBuffer();
  if (arrayBuffer.byteLength === 0) return null;

  // Decode OZT2 → Int16Array
  const { elevation } = await decodeOZT2(arrayBuffer);

  // Convert Int16Array → Float32Array for CesiumJS HeightmapTerrainData
  // Preserve NODATA (-32768) — noDataValue tells Cesium which values are invalid
  const heights = new Float32Array(elevation.length);
  for (let i = 0; i < elevation.length; i++) {
    heights[i] = elevation[i];
  }

  // Bound to a local first: the extra noDataValue key is passed through to
  // Cesium at runtime but is not part of the HeightmapTerrainData structure
  // type, so the literal must not be checked against it directly.
  const structure = { ...HEIGHTMAP_STRUCTURE, noDataValue: OZT2_NODATA };

  return new TDT({
    buffer: heights,
    width: 256,
    height: 256,
    structure,
    childTileMask: level < MAX_TERRAIN_ZOOM ? 15 : 0,
  });
}

/**
 * Fetch and decode a Terrarium PNG server tile.
 * Used as fallback when OZT2 tile is not available.
 */
async function tryPNGTile(
  Cesium: typeof CesiumType,
  level: number,
  x: number,
  y: number,
): Promise<CesiumType.HeightmapTerrainData | null> {
  const url = `${TERRAIN_URL}/${level}/${x}/${y}`;
  // Same presence assertion as the provider factory above.
  const HDT = Cesium.HeightmapTerrainData as typeof CesiumType.HeightmapTerrainData | undefined;
  if (!HDT) return makeFlatTerrain(Cesium, 256);

  try {
    const response = await Cesium.Resource.fetchImage({ url });
    const w = response.width;
    const h = response.height;
    const canvas = document.createElement("canvas");
    canvas.width = w;
    canvas.height = h;
    // A 2D context is always available for a canvas that was just created; the
    // explicit check replaces a non-null assertion and falls through to the
    // catch's flat-terrain fallback if the platform ever refuses one.
    const ctx = canvas.getContext("2d");
    if (!ctx) throw new Error("canvas 2D context unavailable");
    ctx.drawImage(response, 0, 0);
    const imageData = ctx.getImageData(0, 0, w, h);
    const pixels = imageData.data;

    const heights = new Float32Array(w * h);
    for (let i = 0; i < heights.length; i++) {
      const offset = i * 4;
      const R = pixels[offset];
      const G = pixels[offset + 1];
      const B = pixels[offset + 2];
      heights[i] = R * 256 + G + B / 256 - 32768;
    }

  // Same reason as the OZT2 path: noDataValue rides through to Cesium, so the
  // literal is bound to a local to stay out of the structure type check.
  const structure = { ...HEIGHTMAP_STRUCTURE, noDataValue: -32768 };

  return new HDT({
    buffer: heights,
    width: w,
    height: h,
    structure,
    childTileMask: level < MAX_TERRAIN_ZOOM ? 15 : 0,
  });
  } catch {
    return makeFlatTerrain(Cesium, 256);
  }
}

function makeFlatTerrain(Cesium: typeof CesiumType, size: number): CesiumType.HeightmapTerrainData | null {
  // Same presence assertion as the provider factory above.
  const TDT = Cesium.HeightmapTerrainData as typeof CesiumType.HeightmapTerrainData | undefined;
  if (!TDT) return null;
  const flat = new Float32Array(size * size);
  return new TDT({ buffer: flat, width: size, height: size, structure: HEIGHTMAP_STRUCTURE });
}
