/**
 * R2 cache-aside for generated tile data.
 *
 * Tile generation is expensive (~500ms from HuggingFace), but tiles are static
 * for a given zoom/x/y. This module caches generated tiles in R2 so subsequent
 * requests are served from R2 (~10ms) instead of regenerating.
 *
 * Pattern: check R2 → hit? return → miss? generate → store in R2 → return
 *
 * R2 keys: `{type}/v{RENDER_SCHEMA_VERSION}/{z}/{x}/{y}` for edge-rendered
 * types (e.g. "elevation-color/v2/10/350/500") — the version segment orphans
 * bytes rendered by an older schema without touching them. Other types
 * (offline-generated or upstream passthrough bytes) keep unversioned keys.
 * R2 values: raw tile bytes (PNG, terrain, etc.)
 * R2 TTL: managed via R2 lifecycle rules (set in CF dashboard)
 */

import { getR2Bucket } from "./r2-binding";

/**
 * Schema version of the rendered-tile bytes. Stored renders persist up to a
 * year (immutable httpMetadata), so ANY change to how tiles are rendered or
 * decoded must bump this to orphan the old bytes — they are never rewritten
 * until their key is read again. Bumped to 2 when the OZCHNK01 edge-chunk
 * decode was fixed (#124): pre-fix renders could carry -6385m stripes.
 */
export const RENDER_SCHEMA_VERSION = 2;

/**
 * Tile types whose bytes this worker RENDERS from the SRTM decode. Only these
 * get the version segment in their key. Types storing offline-generated or
 * upstream-source bytes (e.g. "ozt2" pre-generated by scripts/upload_ozt2_to_r2.py,
 * "landcover"/"population"/"sentinel2"/GIBS passthroughs) are NOT listed: their
 * bytes do not depend on the edge decoder, so versioning them would only
 * orphan valid data.
 */
const RENDERED_TYPES = new Set(["dem-tile", "elevation-color", "contours", "dem-raw"]);

/** R2 key for one tile; rendered types are versioned so schema changes orphan old bytes. */
function tileKey(type: string, z: number, x: number, y: number): string {
  const version = RENDERED_TYPES.has(type) ? `v${RENDER_SCHEMA_VERSION}/` : "";
  return `${type}/${version}${z}/${x}/${y}`;
}

/**
 * Try to get a cached tile from R2.
 * Returns null on miss or if R2 is unavailable.
 */
export async function r2GetTile(type: string, z: number, x: number, y: number): Promise<ArrayBuffer | null> {
  const bucket = getR2Bucket();
  if (!bucket) return null;

  try {
    const object = await bucket.get(tileKey(type, z, x, y));
    if (!object) return null;
    return await object.arrayBuffer();
  } catch {
    // R2 unavailable or error — fall through to generation
    return null;
  }
}

/**
 * Store a generated tile in R2 for future requests.
 * Best-effort — errors are silently ignored.
 */
export async function r2PutTile(
  type: string,
  z: number,
  x: number,
  y: number,
  data: ArrayBuffer | Uint8Array,
  contentType: string = "application/octet-stream",
): Promise<void> {
  const bucket = getR2Bucket();
  if (!bucket) return;

  try {
    const key = tileKey(type, z, x, y);
    await bucket.put(key, data, {
      httpMetadata: {
        contentType,
        cacheControl: "public, max-age=31536000, immutable",
        cacheExpiry: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000), // 1 year
      },
    });
  } catch {
    // R2 write failed — tile generation still works, just not cached
  }
}
