/**
 * Tests for src/lib/storage/r2-tile-cache.ts — the R2 cache-aside for generated
 * tiles. The R2 bucket binding is emulated in-memory and injected through the
 * setR2BucketProvider() seam.
 */
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

// The global setup file stubs this module out for route tests; restore the real
// implementation here.
vi.mock("@/lib/storage/r2-tile-cache", async (importOriginal) => {
  return await importOriginal<typeof import("@/lib/storage/r2-tile-cache")>();
});

import { r2GetTile, r2PutTile } from "@/lib/storage/r2-tile-cache";
import { setR2BucketProvider } from "@/lib/storage/r2-binding";

interface R2PutOptions {
  httpMetadata?: {
    contentType?: string;
    cacheControl?: string;
    cacheExpiry?: Date;
  };
}

interface FakeR2Object {
  body: ArrayBuffer;
  arrayBuffer: () => Promise<ArrayBuffer>;
  text: () => Promise<string>;
}

interface RecordedPut {
  key: string;
  value: unknown;
  options: R2PutOptions | undefined;
}

interface FakeBucket {
  store: Map<string, FakeR2Object>;
  getCalls: string[];
  puts: RecordedPut[];
  getError: Error | null;
  putError: Error | null;
  get(key: string): Promise<FakeR2Object | null>;
  put(key: string, value: unknown, options?: R2PutOptions): Promise<void>;
  delete(key: string): Promise<void>;
}

function makeObject(body: ArrayBuffer): FakeR2Object {
  return {
    body,
    arrayBuffer: () => Promise.resolve(body),
    text: () => Promise.resolve(new TextDecoder().decode(body)),
  };
}

function createBucket(): FakeBucket {
  const bucket: FakeBucket = {
    store: new Map<string, FakeR2Object>(),
    getCalls: [],
    puts: [],
    getError: null,
    putError: null,
    get: (key: string): Promise<FakeR2Object | null> => {
      bucket.getCalls.push(key);
      if (bucket.getError) return Promise.reject(bucket.getError);
      return Promise.resolve(bucket.store.get(key) ?? null);
    },
    put: (key: string, value: unknown, options?: R2PutOptions): Promise<void> => {
      bucket.puts.push({ key, value, options });
      if (bucket.putError) return Promise.reject(bucket.putError);
      const bytes =
        value instanceof ArrayBuffer
          ? new Uint8Array(value)
          : value instanceof Uint8Array
            ? value
            : new Uint8Array(0);
      const copy = new ArrayBuffer(bytes.byteLength);
      new Uint8Array(copy).set(bytes);
      bucket.store.set(key, makeObject(copy));
      return Promise.resolve();
    },
    delete: (key: string): Promise<void> => {
      bucket.store.delete(key);
      return Promise.resolve();
    },
  };
  return bucket;
}

function tileBytes(size: number, fill: number): ArrayBuffer {
  const out = new ArrayBuffer(size);
  new Uint8Array(out).fill(fill);
  return out;
}

/** 1 year, matching the cacheExpiry written by r2PutTile. */
const YEAR_MS = 365 * 24 * 60 * 60 * 1000;

describe("r2GetTile", () => {
  let bucket: FakeBucket;

  beforeEach(() => {
    bucket = createBucket();
    setR2BucketProvider(() => bucket);
  });

  afterEach(() => {
    setR2BucketProvider(null);
  });

  it("builds the tile key as {type}/v{RENDER_SCHEMA_VERSION}/{z}/{x}/{y}", async () => {
    bucket.store.set("elevation-color/v2/10/350/500", makeObject(tileBytes(4, 1)));

    const result = await r2GetTile("elevation-color", 10, 350, 500);

    expect(bucket.getCalls).toEqual(["elevation-color/v2/10/350/500"]);
    expect(result?.byteLength).toBe(4);
  });

  it("never serves bytes stored under an older schema version", async () => {
    // A pre-#124-era render at the legacy key must be orphaned, not served.
    bucket.store.set("elevation-color/10/350/500", makeObject(tileBytes(4, 1)));

    expect(await r2GetTile("elevation-color", 10, 350, 500)).toBeNull();
    expect(bucket.getCalls).toEqual(["elevation-color/v2/10/350/500"]);
  });

  it("keeps offline-generated and passthrough types on unversioned keys", async () => {
    // "ozt2" holds tiles pre-generated by scripts/upload_ozt2_to_r2.py and
    // "landcover" proxies upstream data — neither depends on the edge
    // decoder, so versioning them would orphan valid bytes for nothing.
    bucket.store.set("ozt2/11/163/395", makeObject(tileBytes(4, 1)));
    bucket.store.set("landcover/8/100/60", makeObject(tileBytes(4, 2)));

    expect(await r2GetTile("ozt2", 11, 163, 395)).not.toBeNull();
    expect(await r2GetTile("landcover", 8, 100, 60)).not.toBeNull();
    expect(bucket.getCalls).toEqual(["ozt2/11/163/395", "landcover/8/100/60"]);
  });

  it("returns null on a cache miss", async () => {
    expect(await r2GetTile("terrain", 7, 12, 34)).toBeNull();
  });

  it("returns the stored bytes", async () => {
    bucket.store.set("contours/v2/7/12/34", makeObject(tileBytes(3, 42)));

    const result = (await r2GetTile("contours", 7, 12, 34)) as ArrayBuffer;
    expect(new Uint8Array(result)[2]).toBe(42);
  });

  it("returns null when no R2 binding is available", async () => {
    setR2BucketProvider(() => {
      throw new Error("not running in a Cloudflare Pages context");
    });

    expect(await r2GetTile("terrain", 7, 12, 34)).toBeNull();
  });

  it("returns null when the provider resolves no binding", async () => {
    setR2BucketProvider(() => null);

    expect(await r2GetTile("terrain", 7, 12, 34)).toBeNull();
  });

  it("returns null when the R2 read fails", async () => {
    bucket.getError = new Error("R2 timeout");

    expect(await r2GetTile("terrain", 7, 12, 34)).toBeNull();
  });
});

describe("r2PutTile", () => {
  let bucket: FakeBucket;
  let now: number;

  beforeEach(() => {
    now = Date.now();
    bucket = createBucket();
    setR2BucketProvider(() => bucket);
  });

  afterEach(() => {
    setR2BucketProvider(null);
  });

  it("stores tile bytes with immutable cache metadata", async () => {
    await r2PutTile("elevation-color", 10, 350, 500, tileBytes(8, 3), "image/png");

    expect(bucket.puts).toHaveLength(1);
    const put = bucket.puts[0];
    expect(put.key).toBe("elevation-color/v2/10/350/500");
    expect(put.options?.httpMetadata?.contentType).toBe("image/png");
    expect(put.options?.httpMetadata?.cacheControl).toBe("public, max-age=31536000, immutable");
    const expiry = put.options?.httpMetadata?.cacheExpiry as Date;
    expect(expiry.getTime()).toBeGreaterThanOrEqual(now + YEAR_MS - 1000);

    // The stored object is readable again through r2GetTile.
    const result = (await r2GetTile("elevation-color", 10, 350, 500)) as ArrayBuffer;
    expect(result.byteLength).toBe(8);
    expect(new Uint8Array(result)[7]).toBe(3);
  });

  it("defaults the content type to application/octet-stream", async () => {
    await r2PutTile("terrain", 7, 12, 34, tileBytes(2, 5));

    const put = bucket.puts[0];
    expect(put.options?.httpMetadata?.contentType).toBe("application/octet-stream");
  });

  it("accepts a Uint8Array payload", async () => {
    await r2PutTile("terrain", 7, 12, 34, new Uint8Array([9, 8, 7]));

    const result = (await r2GetTile("terrain", 7, 12, 34)) as ArrayBuffer;
    expect(Array.from(new Uint8Array(result))).toEqual([9, 8, 7]);
  });

  it("is a no-op when no R2 binding is available", async () => {
    setR2BucketProvider(() => {
      throw new Error("not running in a Cloudflare Pages context");
    });

    await expect(r2PutTile("terrain", 7, 12, 34, tileBytes(2, 1))).resolves.toBeUndefined();
  });

  it("is a no-op when the provider resolves no binding", async () => {
    setR2BucketProvider(() => null);

    await expect(r2PutTile("terrain", 7, 12, 34, tileBytes(2, 1))).resolves.toBeUndefined();
    expect(bucket.puts).toHaveLength(0);
  });

  it("swallows R2 write failures", async () => {
    bucket.putError = new Error("quota exceeded");

    await expect(r2PutTile("terrain", 7, 12, 34, tileBytes(2, 1))).resolves.toBeUndefined();
  });
});
