import { NextRequest, NextResponse } from "next/server";
import { getTileData } from "@/lib/tile";
import { HuggingFaceChunkBackend } from "@/lib/storage/backend";
import { r2GetTile, r2PutTile } from "@/lib/storage/r2-tile-cache";
import { encodeTerrariumPNG } from "@/lib/terrarium-png";
import { CORS_HEADERS, corsPreflightResponse } from "@/lib/cors";

// ─── Format constants ─────────────────────────────────────────────────────────

const FMT_OZT2 = "ozt2" as const;
const FMT_PNG = "png" as const;
type Format = typeof FMT_OZT2 | typeof FMT_PNG;

// R2 key prefixes — separate namespaces for OZT2 vs PNG tiles
const R2_KEY_PREFIX: Record<Format, string> = {
  [FMT_OZT2]: "ozt2",
  [FMT_PNG]: "dem-tile",
};

// MIME types
const CONTENT_TYPE: Record<Format, string> = {
  [FMT_OZT2]: "application/octet-stream",
  [FMT_PNG]: "image/png",
};

/**
 * DEM terrain tile endpoint.
 *
 * Serves elevation tiles in two formats:
 * - OZT2 (default): Custom binary, ~93% smaller than PNG, gradient prediction + Brotli
 * - Terrarium PNG: Legacy format, assembled on-the-fly from HuggingFace SRTM chunks
 *
 * Multi-layer caching:
 * 1. Cloudflare Cache API (edge PoP, <10ms)
 * 2. R2 Storage (durable, ~300ms) — OZT2 pre-generated tiles or PNG tiles
 * 3. HuggingFace (origin, ~1000ms) — PNG assembly only
 *
 * Tile URL pattern: /api/dem-tile/{z}/{x}/{y}
 * Formats: ?format=ozt2 (default for new clients), ?format=png (legacy)
 *
 * OZT2 tiles are pre-generated by scripts/convert_to_ozt2.py and uploaded to R2.
 * The edge runtime cannot Brotli-compress on-the-fly, so OZT2 tiles must exist
 * in R2 before requests. PNG tiles are assembled on-the-fly as fallback.
 *
 * OZT2 format:
 *   Header: 6 bytes [vmin:int16, range:uint16, bits:uint8, flags:uint8]
 *   Body: Brotli-compressed gradient-predicted int16 residuals
 *   Decode: native DecompressionStream("br") — no WASM needed in browser
 */

// Direct backend instance — avoids process.env which may not work on edge
const HF_BACKEND = new HuggingFaceChunkBackend("aliasfox/srtm30m-merged", true);

export const runtime = "edge";

// Cache headers — tiles are deterministic, cache aggressively
const CACHE_HEADERS: Record<string, string> = {
  "Cache-Control": "public, max-age=3600, s-maxage=3600",
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, HEAD, OPTIONS",
};

// Cache namespace for Cloudflare Cache API (edge-level caching)
const DEM_CACHE_NAMESPACE = "dem-tiles-v1";

/**
 * Get cached tile from Cloudflare Cache API.
 * Returns null on miss or if Cache API unavailable.
 */
async function getCfCacheTile(
  z: number, x: number, y: number, format: Format,
): Promise<ArrayBuffer | null> {
  if (typeof caches === "undefined") return null;

  try {
    const cache = await caches.open(DEM_CACHE_NAMESPACE);
    // Format-specific cache key to avoid cross-format contamination
    const key = `/api/dem-tile/${z}/${x}/${y}?fmt=${format}`;
    const cached = await cache.match(key);

    if (cached) {
      const cachedTime = cached.headers.get("x-cached-at");
      if (cachedTime) {
        const age = (Date.now() - parseInt(cachedTime, 10)) / 1000;
        if (age < 3600) {
          return await cached.arrayBuffer();
        }
      } else {
        return await cached.arrayBuffer();
      }
    }
  } catch {
    // Cache API unavailable
  }
  return null;
}

/**
 * Store tile in Cloudflare Cache API for fast edge retrieval.
 */
async function putCfCacheTile(
  z: number, x: number, y: number, data: ArrayBuffer, format: Format,
): Promise<void> {
  if (typeof caches === "undefined") return;

  try {
    const cache = await caches.open(DEM_CACHE_NAMESPACE);
    const key = `/api/dem-tile/${z}/${x}/${y}?fmt=${format}`;
    const headers = new Headers({
      "Content-Type": CONTENT_TYPE[format],
      "Cache-Control": "public, max-age=3600, s-maxage=3600",
      "x-cached-at": String(Date.now()),
      "X-Cache": "HIT",
      "X-Dem-Tile-Format": format,
    });
    cache.put(key, new Response(data, { headers })).catch(() => {});
  } catch {
    // Best-effort caching
  }
}

/**
 * Determine requested format from query string.
 * Defaults to OZT2 for new clients; PNG for legacy / missing values.
 */
function getFormat(request: NextRequest): Format {
  const fmt = request.nextUrl.searchParams.get("format");
  if (fmt === FMT_OZT2) return FMT_OZT2;
  return FMT_PNG;
}

export async function OPTIONS() {
  return corsPreflightResponse();
}

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ z: string; x: string; y: string }> },
) {
  const { z, x, y } = await params;

  // Strip .png extension from y parameter (Next.js includes it in the catch-all)
  const tileYStr = y.replace(/\.png$/, "");

  // Validate zoom level
  const zoom = parseInt(z, 10);
  if (isNaN(zoom) || zoom < 0 || zoom > 14) {
    return NextResponse.json({ error: "Invalid zoom level" }, { status: 400, headers: CORS_HEADERS });
  }

  // Validate tile coordinates
  const tileX = parseInt(x, 10);
  const tileY = parseInt(tileYStr, 10);
  if (isNaN(tileX) || isNaN(tileY)) {
    return NextResponse.json({ error: "Invalid tile coordinates" }, { status: 400, headers: CORS_HEADERS });
  }

  const format = getFormat(request);

  // ── OZT2 request ────────────────────────────────────────────────────────────
  if (format === FMT_OZT2) {
    return serveOZT2Tile(zoom, tileX, tileY);
  }

  // ── PNG request (legacy) ────────────────────────────────────────────────────
  return servePNGTile(zoom, tileX, tileY);
}

/**
 * Serve an OZT2 tile.
 *
 * OZT2 tiles must be pre-generated and stored in R2 (the edge runtime cannot
 * Brotli-compress on-the-fly). If no OZT2 tile exists in R2, we fall back to
 * PNG generation and return a PNG with an X-Dem-Tile-Format: png header so
 * the client knows it received PNG instead of OZT2.
 */
async function serveOZT2Tile(z: number, x: number, y: number): Promise<Response> {
  // Layer 1: Cloudflare Cache API
  try {
    const cfCached = await getCfCacheTile(z, x, y, FMT_OZT2);
    if (cfCached) {
      return new Response(cfCached, {
        headers: {
          ...CACHE_HEADERS,
          "Content-Type": CONTENT_TYPE[FMT_OZT2],
          "Content-Length": String(cfCached.byteLength),
          "X-Dem-Tile-Source": "cf-cache",
          "X-Dem-Tile-Format": FMT_OZT2,
          "X-Cache": "HIT",
        },
      });
    }
  } catch {
    // CF Cache unavailable — fall through
  }

  // Layer 2: R2 OZT2 tiles (pre-generated by convert_to_ozt2.py)
  try {
    const cached = await r2GetTile(R2_KEY_PREFIX[FMT_OZT2], z, x, y);
    if (cached) {
      putCfCacheTile(z, x, y, cached, FMT_OZT2).catch(() => {});
      return new Response(cached, {
        headers: {
          ...CACHE_HEADERS,
          "Content-Type": CONTENT_TYPE[FMT_OZT2],
          "Content-Length": String(cached.byteLength),
          "X-Dem-Tile-Source": "r2-cache",
          "X-Dem-Tile-Format": FMT_OZT2,
          "X-Cache": "HIT",
        },
      });
    }
  } catch {
    // R2 unavailable — fall through
  }

  // Layer 3: OZT2 tile not in R2 — fall back to PNG generation.
  // The client will receive a PNG but should gracefully handle this.
  console.log(`[dem-tile] OZT2 tile not found in R2 for ${z}/${x}/${y}, falling back to PNG`);
  const pngResponse = await servePNGTile(z, x, y);
  // Add header indicating we fell back from OZT2 to PNG
  pngResponse.headers.set("X-Dem-Tile-Format-Fallback", "ozt2-to-png");
  return pngResponse;
}

/**
 * Serve a Terrarium PNG tile (legacy path).
 *
 * Assembles tile on-the-fly from HuggingFace SRTM chunks, caches in R2 and CF.
 */
async function servePNGTile(z: number, x: number, y: number): Promise<Response> {
  // Layer 1: Cloudflare Cache API
  try {
    const cfCached = await getCfCacheTile(z, x, y, FMT_PNG);
    if (cfCached) {
      return new Response(cfCached, {
        headers: {
          ...CACHE_HEADERS,
          "Content-Type": CONTENT_TYPE[FMT_PNG],
          "Content-Length": String(cfCached.byteLength),
          "X-Dem-Tile-Source": "cf-cache",
          "X-Dem-Tile-Format": FMT_PNG,
          "X-Cache": "HIT",
        },
      });
    }
  } catch {
    // CF Cache unavailable — fall through
  }

  // Layer 2: R2 PNG tiles (generated on previous requests)
  try {
    const cached = await r2GetTile(R2_KEY_PREFIX[FMT_PNG], z, x, y);
    if (cached) {
      putCfCacheTile(z, x, y, cached, FMT_PNG).catch(() => {});
      return new Response(cached, {
        headers: {
          ...CACHE_HEADERS,
          "Content-Type": CONTENT_TYPE[FMT_PNG],
          "Content-Length": String(cached.byteLength),
          "X-Dem-Tile-Source": "r2-cache",
          "X-Dem-Tile-Format": FMT_PNG,
          "X-Cache": "HIT",
        },
      });
    }
  } catch {
    // R2 unavailable — fall through to generation
  }

  // Layer 3: Assemble tile from HuggingFace chunks
  try {
    const tileData = await getTileData(z, x, y, HF_BACKEND);
    const png = encodeTerrariumPNG(tileData.data, tileData.width, tileData.height);

    // Store in R2 and CF Cache for future requests
    r2PutTile(R2_KEY_PREFIX[FMT_PNG], z, x, y, png.buffer as ArrayBuffer, "image/png").catch(() => {});
    putCfCacheTile(z, x, y, png.buffer as ArrayBuffer, FMT_PNG).catch(() => {});

    return new Response(png.buffer as ArrayBuffer, {
      headers: {
        ...CACHE_HEADERS,
        "Content-Type": CONTENT_TYPE[FMT_PNG],
        "Content-Length": String(png.byteLength),
        "X-Dem-Tile-Source": "huggingface",
        "X-Dem-Tile-Format": FMT_PNG,
        "X-Cache": "MISS",
      },
    });
  } catch (error) {
    console.error(`DEM tile assembly error: ${z}/${x}/${y}`, error);
    // Return ocean tile for out-of-coverage or errors
    const oceanPng = encodeTerrariumPNG(new Int16Array(256 * 256), 256, 256);
    return new Response(oceanPng.buffer as ArrayBuffer, {
      status: 200,
      headers: {
        ...CACHE_HEADERS,
        "Content-Type": CONTENT_TYPE[FMT_PNG],
        "X-Dem-Tile-Source": "fallback-ocean",
        "X-Dem-Tile-Format": FMT_PNG,
      },
    });
  }
}
