import { NextRequest, NextResponse } from "next/server";
import { getTileData } from "@/lib/tile";
import { HuggingFaceChunkBackend } from "@/lib/storage/backend";
import { RENDER_SCHEMA_VERSION } from "@/lib/storage/edge-cache";
import { encodeTerrariumPNG } from "@/lib/terrarium-png";
import { CORS_HEADERS, corsPreflightResponse } from "@/lib/cors";
import { parseTileParams } from "@/lib/tile-params";

// ─── Format constants ─────────────────────────────────────────────────────────

const FMT_OZT2 = "ozt2" as const;
const FMT_PNG = "png" as const;
type Format = typeof FMT_OZT2 | typeof FMT_PNG;

// OZT2 pre-generated tile origin (HuggingFace dataset — free storage; the
// edge runtime cannot Brotli-compress on-the-fly, so OZT2 is served from the
// pre-generated set). Path scheme matches OZT2HFBackend._tile_url in the
// Python SDK (openzenith/backends/ozt2.py).
const OZT2_HF_REPO = "aliasfox/srtm30m-ozt2-v2";

function ozt2TileUrl(z: number, x: number, y: number): string {
  return `https://huggingface.co/datasets/${OZT2_HF_REPO}/resolve/main/tiles/z${z}/${x}/${y}.ozt2`;
}

// MIME types
const CONTENT_TYPE: Record<Format, string> = {
  [FMT_OZT2]: "application/octet-stream",
  [FMT_PNG]: "image/png",
};

/**
 * DEM terrain tile endpoint.
 *
 * Serves elevation tiles in two formats:
 * - OZT2 (default): Custom binary, ~93% smaller than PNG, gradient prediction + Brotli
 * - Terrarium PNG: Legacy format, assembled on-the-fly from HuggingFace SRTM chunks
 *
 * Multi-layer serving:
 * 1. Cloudflare Cache API (edge PoP, <10ms)
 * 2. HuggingFace (origin, ~300-1000ms) — OZT2 pre-generated tiles or PNG assembly
 *
 * Tile URL pattern: /api/dem-tile/{z}/{x}/{y}
 * Formats: ?format=ozt2 (default for new clients), ?format=png (legacy)
 *
 * OZT2 tiles are pre-generated by scripts/convert_to_ozt2.py and hosted in the
 * HuggingFace dataset aliasfox/srtm30m-ozt2-v2 (free storage). The edge runtime
 * cannot Brotli-compress on-the-fly, so if an OZT2 tile is missing there the
 * request falls back to PNG generation.
 *
 * OZT2 format:
 *   Header: 6 bytes [vmin:int16, range:uint16, bits:uint8, flags:uint8]
 *   Body: Brotli-compressed gradient-predicted int16 residuals
 *   Decode: native DecompressionStream("br") — no WASM needed in browser
 */

// Direct backend instance — avoids process.env which may not work on edge
const HF_BACKEND = new HuggingFaceChunkBackend("aliasfox/srtm30m-merged", true);

export const runtime = "edge";

// Cache headers — tiles are deterministic for a given RENDER_SCHEMA_VERSION
// (the cache namespace above is the invalidation lever), so both the browser
// and the edge hold them immutably. Matches the declared /_headers policy.
const CACHE_TTL_SECONDS = 31536000;
const CACHE_HEADERS: Record<string, string> = {
  "Cache-Control": `public, max-age=${CACHE_TTL_SECONDS}, immutable`,
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, HEAD, OPTIONS",
};

// Cache namespace for Cloudflare Cache API (edge-level caching). Derived from
// RENDER_SCHEMA_VERSION so a decode/render change orphans previously cached
// edge renders instead of serving them (same salt as the R2 keys).
const DEM_CACHE_NAMESPACE = `dem-tiles-v${RENDER_SCHEMA_VERSION}`;

/**
 * Get cached tile from Cloudflare Cache API.
 * Returns null on miss or if Cache API unavailable.
 */
async function getCfCacheTile(z: number, x: number, y: number, format: Format): Promise<ArrayBuffer | null> {
  if (typeof caches === "undefined") return null;

  try {
    const cache = await caches.open(DEM_CACHE_NAMESPACE);
    // Format-specific cache key to avoid cross-format contamination
    const key = `/api/dem-tile/${z}/${x}/${y}?fmt=${format}`;
    const cached = await cache.match(key);

    if (cached) {
      const cachedTime = cached.headers.get("x-cached-at");
      if (cachedTime) {
        const age = (Date.now() - parseInt(cachedTime, 10)) / 1000;
        if (age < CACHE_TTL_SECONDS) {
          return await cached.arrayBuffer();
        }
      }
      // No timestamp → write age unknown → treat as expired and re-render
      // rather than serve bytes of unbounded staleness.
    }
  } catch {
    // Cache API unavailable
  }
  return null;
}

/**
 * Store tile in Cloudflare Cache API for fast edge retrieval.
 */
async function putCfCacheTile(z: number, x: number, y: number, data: ArrayBuffer, format: Format): Promise<void> {
  if (typeof caches === "undefined") return;

  try {
    const cache = await caches.open(DEM_CACHE_NAMESPACE);
    const key = `/api/dem-tile/${z}/${x}/${y}?fmt=${format}`;
    const headers = new Headers({
      "Content-Type": CONTENT_TYPE[format],
      "Cache-Control": `public, max-age=${CACHE_TTL_SECONDS}, immutable`,
      "x-cached-at": String(Date.now()),
      "X-Cache": "HIT",
      "X-Dem-Tile-Format": format,
    });
    cache.put(key, new Response(data, { headers })).catch(() => {});
  } catch {
    // Best-effort caching
  }
}

/**
 * Determine requested format from query string.
 * Defaults to OZT2 for new clients; PNG for legacy / missing values.
 */
function getFormat(request: NextRequest): Format {
  const fmt = request.nextUrl.searchParams.get("format");
  if (fmt === FMT_OZT2) return FMT_OZT2;
  return FMT_PNG;
}

export function OPTIONS() {
  return corsPreflightResponse();
}

export async function GET(request: NextRequest, { params }: { params: Promise<{ z: string; x: string; y: string }> }) {
  const { z, x, y } = await params;

  // Strip .png extension from y parameter (Next.js includes it in the catch-all)
  const tileYStr = y.replace(/\.png$/, "");

  // Strict parse + grid bounds: junk coordinates must not reach DEM assembly.
  const parsed = parseTileParams(z, x, tileYStr, { minZoom: 0, maxZoom: 14 });
  if (!parsed.ok) {
    return NextResponse.json({ error: parsed.message }, { status: parsed.status, headers: CORS_HEADERS });
  }
  const { z: zoom, x: tileX, y: tileY } = parsed;

  const format = getFormat(request);

  // ── OZT2 request ────────────────────────────────────────────────────────────
  if (format === FMT_OZT2) {
    return serveOZT2Tile(zoom, tileX, tileY);
  }

  // ── PNG request (legacy) ────────────────────────────────────────────────────
  return servePNGTile(zoom, tileX, tileY);
}

/**
 * Fetch a pre-generated OZT2 tile from the HuggingFace dataset.
 * Returns null when the tile is missing (out of the generated range) or the
 * fetch fails.
 */
async function fetchOzt2Tile(z: number, x: number, y: number): Promise<ArrayBuffer | null> {
  const response = await fetch(ozt2TileUrl(z, x, y), { redirect: "follow" });
  if (!response.ok) return null;
  return await response.arrayBuffer();
}

/**
 * Serve an OZT2 tile.
 *
 * OZT2 tiles are pre-generated and hosted on HuggingFace (the edge runtime
 * cannot Brotli-compress on-the-fly). If no OZT2 tile exists there, we fall
 * back to PNG generation and return a PNG with an X-Dem-Tile-Format: png
 * header so the client knows it received PNG instead of OZT2.
 */
async function serveOZT2Tile(z: number, x: number, y: number): Promise<Response> {
  // Layer 1: Cloudflare Cache API
  try {
    const cfCached = await getCfCacheTile(z, x, y, FMT_OZT2);
    if (cfCached) {
      return new Response(cfCached, {
        headers: {
          ...CACHE_HEADERS,
          "Content-Type": CONTENT_TYPE[FMT_OZT2],
          "Content-Length": String(cfCached.byteLength),
          "X-Dem-Tile-Source": "cf-cache",
          "X-Dem-Tile-Format": FMT_OZT2,
          "X-Cache": "HIT",
        },
      });
    }
  } catch {
    // CF Cache unavailable — fall through
  }

  // Layer 2: pre-generated OZT2 tiles from the HuggingFace dataset
  try {
    const ozt2 = await fetchOzt2Tile(z, x, y);
    if (ozt2) {
      putCfCacheTile(z, x, y, ozt2, FMT_OZT2).catch(() => {});
      return new Response(ozt2, {
        headers: {
          ...CACHE_HEADERS,
          "Content-Type": CONTENT_TYPE[FMT_OZT2],
          "Content-Length": String(ozt2.byteLength),
          "X-Dem-Tile-Source": "huggingface",
          "X-Dem-Tile-Format": FMT_OZT2,
          "X-Cache": "MISS",
        },
      });
    }
  } catch {
    // HF unavailable — fall through to PNG
  }

  // Layer 3: OZT2 tile not available — fall back to PNG generation.
  // The client will receive a PNG but should gracefully handle this.
  // Prod diagnostics ride the X-Dem-Tile-Format-Fallback header; the log is
  // dev-only so routine fallbacks don't spam edge logs.
  if (process.env.NODE_ENV === "development") {
    console.warn(`[dem-tile] OZT2 tile not found for ${z}/${x}/${y}, falling back to PNG`);
  }
  const pngResponse = await servePNGTile(z, x, y);
  // Add header indicating we fell back from OZT2 to PNG
  pngResponse.headers.set("X-Dem-Tile-Format-Fallback", "ozt2-to-png");
  return pngResponse;
}

/**
 * Serve a Terrarium PNG tile (legacy path).
 *
 * Assembles tile on-the-fly from HuggingFace SRTM chunks, caches in CF Cache.
 */
async function servePNGTile(z: number, x: number, y: number): Promise<Response> {
  // Layer 1: Cloudflare Cache API
  try {
    const cfCached = await getCfCacheTile(z, x, y, FMT_PNG);
    if (cfCached) {
      return new Response(cfCached, {
        headers: {
          ...CACHE_HEADERS,
          "Content-Type": CONTENT_TYPE[FMT_PNG],
          "Content-Length": String(cfCached.byteLength),
          "X-Dem-Tile-Source": "cf-cache",
          "X-Dem-Tile-Format": FMT_PNG,
          "X-Cache": "HIT",
        },
      });
    }
  } catch {
    // CF Cache unavailable — fall through
  }

  // Layer 2: Assemble tile from HuggingFace chunks
  try {
    const tileData = await getTileData(z, x, y, HF_BACKEND);
    const png = encodeTerrariumPNG(tileData.data, tileData.width, tileData.height);

    // Store in CF Cache for future requests
    putCfCacheTile(z, x, y, png.buffer as ArrayBuffer, FMT_PNG).catch(() => {});

    return new Response(png.buffer as ArrayBuffer, {
      headers: {
        ...CACHE_HEADERS,
        "Content-Type": CONTENT_TYPE[FMT_PNG],
        "Content-Length": String(png.byteLength),
        "X-Dem-Tile-Source": "huggingface",
        "X-Dem-Tile-Format": FMT_PNG,
        "X-Cache": "MISS",
      },
    });
  } catch {
    // getTileData returns an all-NODATA grid (HTTP 200) for genuine ocean /
    // out-of-coverage tiles, so reaching this catch means assembly itself
    // failed (HuggingFace outage, decode error). Report 502 instead of
    // serving a flat 0m ocean tile that masks the outage.
    return Response.json(
      { error: "Failed to assemble DEM tile" },
      { status: 502, headers: { ...CORS_HEADERS, "Content-Type": "application/json" } },
    );
  }
}
