name = "openzenith"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
STORAGE_BACKEND = "huggingface"
HF_REPO = "aliasfox/srtm30m-merged"
USE_MERGED = "true"

# OpenSky Network API (OAuth2 client credentials)
OPENSKY_CLIENT_ID = "micheal.l.c.kinney@gmail.com-api-client"
OPENSKY_CLIENT_SECRET = "GXJMhLWuATBGxPoxJz9m7A6KA4NFLYgz"

# AISstream.io (free vessel tracking WebSocket)
AISSTREAM_KEY = "6f699e3655fd824a0f6a03eda802d19526305d0e"
